production:
  url: http://emailmarketing.locaweb.com.br
  login: meu_login_de_prod
  password: minha_senha_de_prod
preprod:
  url: http://qa0031.preprod.locaweb.com.br
  login: meu_login_de_preprod
  password: minha_senha_de_preprod
sysint:
  url: http://emailmarketing.systemintegration.locaweb.com.br
  login: meu_login_de_sysint
  password: minha_senha_de_sysint
development:
  url: http://localhost:3000
  login: admin@admin.com
  password: teste123
